# Packaging environments
wheezy:
  build: ./packagingenv/wheezy
  extends:
    file: docker-compose.override.yml
    service: suite

jessie:
  build: ./packagingenv/jessie
  extends:
    file: docker-compose.override.yml
    service: suite

trusty:
  build: ./packagingenv/trusty
  extends:
    file: docker-compose.override.yml
    service: suite

xenial:
  build: ./packagingenv/xenial
  extends:
    file: docker-compose.override.yml
    service: suite

el7:
  build: ./packagingenv/centos7
  extends:
    file: docker-compose.override.yml
    service: suite

el6:
  build: ./packagingenv/centos6
  extends:
    file: docker-compose.override.yml
    service: suite

# Testing environments
wheezy-test:
  build: ./testingenv/wheezy
  extends:
    file: docker-compose.override.yml
    service: suite-test

jessie-test:
  build: ./testingenv/jessie
  extends:
    file: docker-compose.override.yml
    service: suite-test

trusty-test:
  build: ./testingenv/trusty
  extends:
    file: docker-compose.override.yml
    service: suite-test

xenial-test:
  build: ./testingenv/xenial
  extends:
    file: docker-compose.override.yml
    service: suite-test

el7-test:
  build: ./testingenv/centos7
  extends:
    file: docker-compose.override.yml
    service: suite-test

el6-test:
  build: ./testingenv/centos6
  extends:
    file: docker-compose.override.yml
    service: suite-test
