wheezy:
  build: ./packagingenv/wheezy
  extends:
    file: docker-compose.override.yml
    service: suite

jessie:
  build: ./packagingenv/jessie
  extends:
    file: docker-compose.override.yml
    service: suite

trusty:
  build: ./packagingenv/trusty
  extends:
    file: docker-compose.override.yml
    service: suite

el7:
  build: ./packagingenv/centos7
  extends:
    file: docker-compose.override.yml
    service: suite

el6:
  build: ./packagingenv/centos6
  extends:
    file: docker-compose.override.yml
    service: suite
